#!/bin/bash
# Quick reference for audio integration tests
# Located in: examples/

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " AUDIO INTEGRATION TESTS - QUICK REFERENCE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 Location: examples/"
echo ""
echo "🧪 INDIVIDUAL TESTS"
echo ""
echo "  1. Hardware Detection"
echo "     $ python examples/test_hardware_detection.py"
echo "     Tests: Can we find audio devices?"
echo ""
echo "  2. Stream Open/Close"
echo "     $ python examples/test_stream_open_close.py"
echo "     Tests: Can we open/close input & output streams?"
echo ""
echo "  3. Audio Playback"
echo "     $ python examples/test_playback.py"
echo "     Tests: Can we play audio (sine wave + silence)?"
echo ""
echo "  4. Audio Recording"
echo "     $ python examples/test_recording.py"
echo "     Tests: Can we record from mic and save to WAV?"
echo ""
echo "🚀 RUN ALL TESTS"
echo ""
echo "  $ python examples/run_all_audio_tests.py"
echo "  Runs all 4 tests with summary report"
echo ""
echo "📖 DOCUMENTATION"
echo ""
echo "  $ cat examples/AUDIO_TESTS_README.md"
echo "  Full guide with expected outputs and troubleshooting"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✓ All tests PASSED on current hardware"
echo "✓ Ready for CI/CD integration"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
