#!/bin/bash
# Quick reference for audio integration tests
# Located in: examples/

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " AUDIO INTEGRATION TESTS - QUICK REFERENCE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 Location: examples/"
echo ""
echo "🧪 INDIVIDUAL TESTS"
echo ""
echo "  1. Hardware Detection"
echo "     $ python examples/test_hardware_detection.py"
echo "     Tests: Can we find audio devices?"
echo ""
echo "  2. Stream Open/Close"
echo "     $ python examples/test_stream_open_close.py"
echo "     Tests: Can we open/close input & output streams?"
echo ""
echo "  3. Audio Playback"
echo "     $ python examples/test_playback.py"
echo "     Tests: Can we play audio (sine wave + silence)?"
echo ""
echo "  4. Audio Recording"
echo "     $ python examples/test_recording.py"
echo "     Tests: Can we record from mic and save to WAV?"
echo ""
echo "  5. ASR Engine Flow"
echo "     $ python examples/test_asr_integration.py"
echo "     Tests: Can we initialize ASREngine and capture chunks?"
echo ""
echo "  6. ASR with TTS"
echo "     $ python examples/test_asr_with_tts.py"
echo "     Tests: Can ASREngine transcribe TTS audio output?"
echo ""
echo "  7. ASR Recording Validation"
echo "     $ python examples/test_asr_recording_validation.py"
echo "     Tests: Can we transcribe voice recordings captured from the microphone?"
echo ""
echo "  8. VAD Standalone Flow"
echo "     $ python examples/test_vad_standalone.py"
echo "     Tests: Can VADEngine detect voice segments and handle resampling?"
echo ""
echo "  9. TTS Lifecycle & Utils"
echo "     $ python examples/test_tts_lifecycle_and_utils.py"
echo "     Tests: Can TTSEngine handle non-blocking playback, interrupts, and custom audio formatting?"
echo ""
echo "🚀 RUN ALL TESTS"
echo ""
echo "  $ python examples/run_all_audio_tests.py"
echo "  Runs all 9 tests with summary report"
echo ""
echo "📖 DOCUMENTATION"
echo ""
echo "  $ cat examples/AUDIO_TESTS_README.md"
echo "  Full guide with expected outputs and troubleshooting"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✓ All tests PASSED on current hardware"
echo "✓ Ready for CI/CD integration"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
